---
title: "Amniote Mass"
author: "Erin Keleske"
date: "3/22/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r libraries, include=FALSE}
# Library download

if(!require(ggplot2)) {
  install.packages("ggplot2");
  require(ggplot2)}

if(!require(raster)) {
  install.packages("raster");
  require(raster)}

if(!require(readr)) {
  install.packages("readr");
  require(readr)}

if(!require(sp)) {
  install.packages("sp");
  require(sp)}

```

## Downloading data 

Raw data originated from: 

  Nathan P. Myhrvold, Elita Baldridge, Benjamin Chan, Dhileep Sivam, Daniel L.     Freeman, and S. K. Morgan Ernest. 2015. An amniote life-history database to      perform comparative analyses with birds, mammals, and reptiles. Ecology          96:3109.http://dx.doi.org/10.1890/15-0846.1

Data can be found [here](http://www.esapubs.org/archive/ecol/E096/269/#data).

```{r data, include=FALSE}
amniote_raw <- read_csv("./data/Amniote_Database_Aug_2015.csv")
```



